// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package resources

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3dd19239DecodeMainResources(in *jlexer.Lexer, out *Resources) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "file_name":
			out.FileName = string(in.String())
		case "link":
			out.Link = string(in.String())
		case "size":
			out.Size = string(in.String())
		case "update_time":
			out.UpdateTime = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3dd19239EncodeMainResources(out *jwriter.Writer, in Resources) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(in.FileName))
	}
	{
		const prefix string = ",\"link\":"
		out.RawString(prefix)
		out.String(string(in.Link))
	}
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix)
		out.String(string(in.Size))
	}
	{
		const prefix string = ",\"update_time\":"
		out.RawString(prefix)
		out.String(string(in.UpdateTime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Resources) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3dd19239EncodeMainResources(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Resources) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3dd19239EncodeMainResources(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Resources) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3dd19239DecodeMainResources(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Resources) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3dd19239DecodeMainResources(l, v)
}
