// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package reply

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson95c6beaaDecodeMainReply(in *jlexer.Lexer, out *JsonReply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = uint8(in.Uint8())
		case "content":
			if in.IsNull() {
				in.Skip()
				out.Content = nil
			} else {
				out.Content = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson95c6beaaEncodeMainReply(out *jwriter.Writer, in JsonReply) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Uint8(uint8(in.Status))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Content)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JsonReply) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson95c6beaaEncodeMainReply(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JsonReply) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson95c6beaaEncodeMainReply(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JsonReply) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson95c6beaaDecodeMainReply(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JsonReply) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson95c6beaaDecodeMainReply(l, v)
}
